# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

AllCops:
  DisplayStyleGuide: true
  ExtraDetails: true


Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma


# Disables
Layout/AccessModifierIndentation: { Enabled: false }
Metrics/AbcSize: { Enabled: false }
Metrics/BlockLength: { Enabled: false }
Metrics/CyclomaticComplexity: { Enabled: false }
Metrics/LineLength: { Enabled: false }
Metrics/MethodLength: { Enabled: false }
Metrics/ModuleLength: { Enabled: false }
Metrics/PerceivedComplexity: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/RegexpLiteral: { Enabled: false }
Style/SpaceInsideStringInterpolation: { Enabled: false }
Style/StringLiterals: { Enabled: false }
